name: Daily Commit Workflow

on:
  schedule:
    - cron: '15 6 * * *'  # Runs daily at 6:15 UTC
  workflow_dispatch:  # Optional: Allows manual trigger from UI

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add commit - 24f2005647@ds.study.iitm.ac.in
        run: |
          echo "Daily update - $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily update"
          git push
